### ISSUE TITLE
Unable to run interactiveSim.py on windows with docker

### ISSUE THREAD

**Issue by MeshLora** [meshtastic/Meshtasticator#17]
![image](https://github.com/user-attachments/assets/75937bde-5c64-438b-a8cb-b89a31b45005)
Hi, i am unable to run the simulation on windows with Docker

**Comment by GUVWAF** [comment]
Hi, sorry for the late response. I don't have much experience with Docker under Windows, but it looked like it couldn't get the container to run. Did you resolve this eventually?

**Comment by alexberry** [comment]
This issue does not appear to be limited to Windows, I have the same issue on Fedora. I raised issue #18 and PR #19 with a fix.

**Comment by GUVWAF** [comment]
Fixed by #19.
